In [ ]:
# Import necessary libraries
import pandas as pd
import pandas as pd
import re
import numpy as np

In [ ]:
# Load the raw combined temperature data
data = pd.read_csv("combined_temperature.csv")

In [ ]:
# Display the data to see its structure
data

                  Country        Year  Annual_Mean  Five_Year_Smooth Code
0      Dominican Republic  1901-01-01        23.71             23.65  DOM
1      Dominican Republic  1902-01-01        23.40             23.52  DOM
2      Dominican Republic  1903-01-01        23.45             23.38  DOM
3      Dominican Republic  1904-01-01        23.03             23.26  DOM
4      Dominican Republic  1905-01-01        23.44             23.16  DOM
...                   ...         ...          ...               ...  ...
20735         Switzerland  2018-01-01         7.68              7.27  CHE
20736         Switzerland  2019-01-01         7.31              7.34  CHE
20737         Switzerland  2020-01-01         7.64              7.38  CHE
20738         Switzerland  2021-01-01         6.39              7.42  CHE
20739         Switzerland  2022-01-01         8.08              7.44  CHE

[20740 rows x 5 columns]

In [ ]:
# Check the data types of each column
print(data.dtypes)

Country              object
Year                 object
Annual_Mean         float64
Five_Year_Smooth    float64
Code                 object
dtype: object

In [ ]:
# Rename columns to remove spaces and special characters
data = data.rename(columns={
    "Annual Mean": "Annual_Mean",
    "5-yr smooth": "Five_Year_Smooth"
})

In [ ]:
# Display the cleaned data
data

                  Country        Year  Annual_Mean  Five_Year_Smooth Code
0      Dominican Republic  1901-01-01        23.71             23.65  DOM
1      Dominican Republic  1902-01-01        23.40             23.52  DOM
2      Dominican Republic  1903-01-01        23.45             23.38  DOM
3      Dominican Republic  1904-01-01        23.03             23.26  DOM
4      Dominican Republic  1905-01-01        23.44             23.16  DOM
...                   ...         ...          ...               ...  ...
20735         Switzerland  2018-01-01         7.68              7.27  CHE
20736         Switzerland  2019-01-01         7.31              7.34  CHE
20737         Switzerland  2020-01-01         7.64              7.38  CHE
20738         Switzerland  2021-01-01         6.39              7.42  CHE
20739         Switzerland  2022-01-01         8.08              7.44  CHE

[20740 rows x 5 columns]

In [ ]:
# Save the cleaned data to a new CSV file
data.to_csv("cleaned_temperature.csv", index=False)